### ISSUE TITLE
Fix workflow "PR-Packager" (pr-packager.yml)

### ISSUE THREAD

**Issue by Spheres-cu** [Garulf/Browser-History#25]
For the workflow : "PR-Packager" (pr-packager.yml) @Garulf you shoul change the action uses: actions/{action_name}@v2  to actions/{action_name}@v4 or to actions/{action_name}@v5 to avoid errors in action compilation.

Example:

```
name: "PR-Packager"
on:
  workflow_dispatch:
  pull_request:
env:
  PYTHON_VER: 3.8
jobs:
  deps:
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VER }}
      - uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r ./requirements.txt -t ./lib
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./**
            !./.git/
            !./README.md/
            !./.github/
            !./assets/

```
